const hallen = [
  {
    hall_name: "DAV Augsburg",
    street_address: "Valentinstag 2",
    city: "Buchsdehuette",
    postal_code: "00015",
    owner_username: "DAV Augsburg",
    routes: [
      {
        routeName: "Fingerpine",
        climbingHallName: "DAV Augsburg",
        Sector: "A",
        LevelOfDifficulty: "6+",
        color: "blue",
        lineNumber: "261",
        Tilt: false,
      },
      {
        routeName: "te",
        climbingHallName: "DAV Augsburg",
        Sector: "C",
        LevelOfDifficulty: "1",
        color: "yellow",
        lineNumber: "099",
        Tilt: false,
      },
      {
        routeName: "Nicol",
        climbingHallName: "DAV Augsburg",
        Sector: "D",
        LevelOfDifficulty: "9-",
        color: "red",
        lineNumber: "999",
        Tilt: true,
      },
      {
        routeName: "Popipe",
        climbingHallName: "DAV Augsburg",
        Sector: "X",
        LevelOfDifficulty: "10+",
        color: "grey",
        lineNumber: "444",
        Tilt: true,
      },
    ],
  },
  {
    hall_name: "D Horsens",
    street_address: "Hors 2",
    city: "Horsens",
    postal_code: "56185",
    owner_username: "D Horsens",
    routes: [
      {
        routeName: "Fingerpine",
        climbingHallName: "DAV Augsburg",
        Sector: "A",
        LevelOfDifficulty: "6+",
        color: "blue",
        lineNumber: "261",
        Tilt: false,
      },
      {
        routeName: "te",
        climbingHallName: "DAV Augsburg",
        Sector: "C",
        LevelOfDifficulty: "1",
        color: "yellow",
        lineNumber: "099",
        Tilt: false,
      },
      {
        routeName: "Nicol",
        climbingHallName: "DAV Augsburg",
        Sector: "D",
        LevelOfDifficulty: "9-",
        color: "red",
        lineNumber: "999",
        Tilt: true,
      },
      {
        routeName: "Popipe",
        climbingHallName: "DAV Augsburg",
        Sector: "X",
        LevelOfDifficulty: "10+",
        color: "grey",
        lineNumber: "444",
        Tilt: true,
      },
    ],
  },
  {
    hall_name: "Hund Ahaaa",
    street_address: "Hundstrasse 2",
    city: "Ahaaa",
    postal_code: "56482",
    owner_username: "Hund Ahaaa",
    routes: [
      {
        routeName: "Fingerpine",
        climbingHallName: "DAV Augsburg",
        Sector: "A",
        LevelOfDifficulty: "6+",
        color: "blue",
        lineNumber: "261",
        Tilt: false,
      },
      {
        routeName: "te",
        climbingHallName: "DAV Augsburg",
        Sector: "C",
        LevelOfDifficulty: "1",
        color: "yellow",
        lineNumber: "099",
        Tilt: false,
      },
      {
        routeName: "Nicol",
        climbingHallName: "DAV Augsburg",
        Sector: "D",
        LevelOfDifficulty: "9-",
        color: "red",
        lineNumber: "999",
        Tilt: true,
      },
      {
        routeName: "Popipe",
        climbingHallName: "DAV Augsburg",
        Sector: "X",
        LevelOfDifficulty: "10+",
        color: "grey",
        lineNumber: "444",
        Tilt: true,
      },
    ],
  },
  {
    hall_name: "Katze Ayooo",
    street_address: "Katzenstrasse 2",
    city: "Ayooo",
    postal_code: "51485",
    owner_username: "Katze Ayooo",
    routes: [
      {
        routeName: "Fingerpine",
        climbingHallName: "DAV Augsburg",
        Sector: "A",
        LevelOfDifficulty: "6+",
        color: "blue",
        lineNumber: "261",
        Tilt: false,
      },
      {
        routeName: "te",
        climbingHallName: "DAV Augsburg",
        Sector: "C",
        LevelOfDifficulty: "1",
        color: "yellow",
        lineNumber: "099",
        Tilt: false,
      },
      {
        routeName: "Nicol",
        climbingHallName: "DAV Augsburg",
        Sector: "D",
        LevelOfDifficulty: "9-",
        color: "red",
        lineNumber: "999",
        Tilt: true,
      },
      {
        routeName: "Popipe",
        climbingHallName: "DAV Augsburg",
        Sector: "X",
        LevelOfDifficulty: "10+",
        color: "grey",
        lineNumber: "444",
        Tilt: true,
      },
    ],
  },
];
export default hallen;