const routes = [
  {
    route_name: "Evening Ember",
    climbingHallName: "DAV Kletterzentrum Augbsurg",
    sector: "L",
    level_of_difficulty: "7+",
    color: "darkgoldenrod",
    line_number: "124",
    numberOfAttempts: 0,
    tilt: true,
  },
  {
    route_name: "Dawnbreak",
    climbingHallName: "DAV Kletterzentrum Augbsurg",
    sector: "M",
    level_of_difficulty: "6-",
    color: "darkmagenta",
    line_number: "135",
    numberOfAttempts: 0,
    tilt: true,
  },
  {
    route_name: "Sunset Silhouette",
    climbingHallName: "DAV Kletterzentrum Augbsurg",
    sector: "N",
    level_of_difficulty: "7",
    color: "crimson",
    line_number: "143",
    numberOfAttempts: 0,
    tilt: false,
  },
  {
    route_name: "Daydream Delight",
    climbingHallName: "DAV Kletterzentrum Augbsurg",
    sector: "O",
    level_of_difficulty: "6+",
    color: "mediumslateblue",
    line_number: "156",
    numberOfAttempts: 0,
    tilt: false,
  },
  {
    route_name: "Moonlit Madness",
    climbingHallName: "DAV Kletterzentrum Augbsurg",
    sector: "P",
    level_of_difficulty: "7",
    color: "darkolivegreen",
    line_number: "162",
    numberOfAttempts: 0,
    tilt: true,
  },
  {
    route_name: "Azure Ascend",
    climbingHallName: "DAV Kletterzentrum Augbsurg",
    sector: "Q",
    level_of_difficulty: "8",
    color: "blue",
    line_number: "169",
    numberOfAttempts: 0,
    tilt: true,
  },
  {
    route_name: "Verdant Venture",
    climbingHallName: "DAV Kletterzentrum Augbsurg",
    sector: "R",
    level_of_difficulty: "5",
    color: "green",
    line_number: "172",
    numberOfAttempts: 1,
    tilt: false,
  },
  {
    route_name: "Crimson Climb",
    climbingHallName: "DAV Kletterzentrum Augbsurg",
    sector: "S",
    level_of_difficulty: "6+",
    color: "crimson",
    line_number: "185",
    numberOfAttempts: 2,
    tilt: true,
  },
  {
    route_name: "Pinnacle of Dawn",
    climbingHallName: "DAV Kletterzentrum Augbsurg",
    sector: "T",
    level_of_difficulty: "7-",
    color: "orange",
    line_number: "193",
    numberOfAttempts: 3,
    tilt: false,
  },
  {
    route_name: "Twilight's Last Gleaming",
    climbingHallName: "DAV Kletterzentrum Augbsurg",
    sector: "U",
    level_of_difficulty: "8+",
    color: "violet",
    line_number: "197",
    numberOfAttempts: 1,
    tilt: true,
  },
];
export default routes;
